services:
  - type: web
    name: fabrication-billing-system
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
    envVars:
      - key: RENDER
        value: 1
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SESSION_SECRET
        generateValue: true